# Generated by Django 4.2.5 on 2023-09-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_categoria_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default='Nenhuma', on_delete=django.db.models.deletion.CASCADE, to='clientes.categoria'),
        ),
    ]
