# Generated by Django 4.2.5 on 2023-09-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_produto_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='comprador',
        ),
    ]
