# Generated by Django 4.2.5 on 2023-09-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='Produto',
            new_name='produto',
        ),
    ]
